name: CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  # pre-commit:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6.0.2
  #     - uses: actions/setup-python@v6
  #     - uses: pre-commit/action@v3.0.1

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 10 
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          environment-file: ci/env.yml
          activate-environment: pcnv-dev
          auto-activate-base: false

      - name: Test build distribution
        shell: bash -l {0}
        run: |
          git clean -xdf
          pyproject-build

      - name: Install source
        shell: bash -l {0}
        run: python -m pip install .

      - name: List installed packages
        shell: bash -l {0}
        run: conda list

      - name: Run tests
        shell: bash -l {0}
        run: python -m pytest -s --cov=pyncv --cov-report=xml .

